# Generated by Django 2.2.5 on 2019-10-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ('-id',), 'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlecomment_reply_comments', to='comment.ArticleComment', verbose_name='被回复的评论'),
        ),
    ]
