"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys

# 项目根目录，示例：/home/mysite
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# 设置生产环境的配置文件
config_file_path = os.path.join(BASE_DIR, "prod_settings.py")
if os.path.exists(config_file_path):
    import prod_settings as settings

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

SECRET_KEY = '4d#v@ww8hq@)q5^iw@s)_%z@ltzn3y3(dsvaft981ue@ejff(q'

# 生产环境要设置为False，本地测试的时候设置为True
DEBUG = False

# 允许的IP，*表示所有
ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # django-allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # 允许以github账号登陆
    'allauth.socialaccount.providers.github',
    # django-haystack
    'haystack',
    #  django-ckeditor
    'ckeditor',
    'ckeditor_uploader',

    'user.apps.UserConfig',
    'home.apps.HomeConfig',
    'blog.apps.BlogConfig',
    'comment.apps.CommentConfig',
]

"""
django-allauth之所以设置SIT_ID, 是因为用到django的“site”
django site相关内容详见：https://docs.djangoproject.com/en/2.2/ref/contrib/sites/#s-enabling-the-sites-framework
"""
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


DATABASES = {
    # sqlite3
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }

    # mysql
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '47.107.136.2',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': '123456',
        'NAME': 'mysite',
        'OPTIONS': {'charset': 'utf8mb4'},
    }

}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# 静态文件设置
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# 部署时，收集的静态文件放到该目录
STATIC_ROOT = os.path.join(BASE_DIR, 'collectstatic')

# 媒体文件收集
MEDIA_URL = 'static/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 项目日志设置
WORK_PATH = os.path.abspath(os.path.dirname(__file__))
PRJ_NAME = os.path.split(WORK_PATH)[-1]
LOG_PATH = "/var/log/sweeneys/mysite/%s.log" % PRJ_NAME
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': 'sweeneys %(levelname)s %(asctime)s %(module)s %(funcName)s %(lineno)d %(message)s'
        },
        'simple': {
            'format': 'sweeneys %(levelname)s %(message)s'
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': LOG_PATH,  # 必须保证用户对该目录有读写权限
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins', 'file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'default': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}

# 自定义用户模型user是应用名，USER是模型名
AUTH_USER_MODEL = 'user.USER'

# 网站默认设置和上下文信息
SITE_END_TITLE = os.getenv('Sweeneys_SITE_END_TITLE', 'Sweeneys')
SITE_DESCRIPTION = os.getenv('Sweeneys_SITE_DESCRIPTION', 'Sweeneys的官方网站')
SITE_KEYWORDS = os.getenv('Sweeneys_SITE_KEYWORDS', 'Sweeneys,Python,Django, Nginx, Gunicorn, Supervisor, uWSGI, WSGI')

# django-allauth设置用户注册的时候必须填写邮箱地址
ACCOUNT_EMAIL_REQUIRED = True

#  Django发送邮件设置
EMAIL_HOST = 'smtp.qq.com'
EMAIL_HOST_USER = 'sweeneys@qq.com'
EMAIL_HOST_PASSWORD = 'vfibizonnhwfbdih'
EMAIL_PORT = 465
EMAIL_TIMEOUT = 5
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'sweeneys@qq.com'

"""
Django-allauth注册邮箱验证.有三种值：
mandatory: 强制验证email，否则使用用户名和邮箱名都不可用登陆。
optional: 不强制验证email, 发送验证邮件，不验证邮箱只能使用用户名登陆。
none: 不强制验证email，不发送验证邮件，不验证邮箱使用用户名和邮箱名都可以登陆。
"""
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# 设置邮箱确认的有效时间
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 0.01

#  django-allauth设置验证邮箱后自动登陆
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/accounts/login'

# django-allauth设置登录成功后重定向的页面，默认是/accounts/profile/
LOGIN_REDIRECT_URL = "/"

# django-allauth设置直接退出，不用确认
ACCOUNT_LOGOUT_ON_GET = True

# django-allauth设置可以用用户名也可以用邮箱登陆
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend"
)

# 统一分页设置
BASE_PAGINATE_BY = 3
BASE_PAGINATE_ORPHANS = 5
# django-haystack 配置
HAYSTACK_CONNECTIONS = {
    # 'default': {
    #     'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
    #     'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    # },
    'default': {
        # 选择语言解析器为自己更换的结巴分词
        'ENGINE': 'blog.whoosh_cn_backend.WhooshEngine',
        # 设置索引文件的保存位置为项目根目录下，目录名为whoosh_index
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
# 指定索引更新的时间
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# 指定django-ckeditor文件上传路径,这是一个相对路径，相对于MEDIA_ROOT的路径
CKEDITOR_UPLOAD_PATH = "ckeditor_uploads/"

# ckeditor
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_Full': [
            ['Source', '-', 'Save', 'NewPage', 'DocProps', 'Preview', 'Print', '-', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],

            ['Find', 'Replace', '-', 'SelectAll', '-', 'SpellChecker', 'Scayt'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
            '/',

            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
             'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe'],
            '/',
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks', '-', 'About'],

        ],
        'toolbar': 'Full',
    }
}

# 状态
STATUS = (
    (1, "启用"),
    (0, "禁用"),
)
